#if !canImport(ObjectiveC)
import XCTest

extension CompoundIntervalDescriptorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompoundIntervalDescriptorTests = [
        ("testInitTwoSpelledPitchesAscendingMajorTenth", testInitTwoSpelledPitchesAscendingMajorTenth),
        ("testInitTwoSpelledPitchesAscendingMinorSecond", testInitTwoSpelledPitchesAscendingMinorSecond),
        ("testInitTwoSpelledPitchesAscendingMinorSixth", testInitTwoSpelledPitchesAscendingMinorSixth),
        ("testInitTwoSpelledPitchesDescendingMajorSecond", testInitTwoSpelledPitchesDescendingMajorSecond),
        ("testInitTwoSpelledPitchesDescendingPerfectEleventh", testInitTwoSpelledPitchesDescendingPerfectEleventh),
        ("testInitTwoSpelledPitchesUnison", testInitTwoSpelledPitchesUnison),
    ]
}

extension FlowNetworkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlowNetworkTests = [
        ("testFlowNetworkMaskEmpty", testFlowNetworkMaskEmpty),
        ("testFlowNetworkMaskSquared", testFlowNetworkMaskSquared),
        ("testMinimumCut", testMinimumCut),
        ("testPitchSpellingTestCase", testPitchSpellingTestCase),
        ("testUnreachableMinimumCut", testUnreachableMinimumCut),
    ]
}

extension FlowNodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlowNodeTests = [
        ("testDecodableFlowNode", testDecodableFlowNode),
        ("testEncodableFlowNode", testEncodableFlowNode),
    ]
}

extension LetterNameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LetterNameTests = [
        ("testDisplacedUnison", testDisplacedUnison),
        ("testLetterNameSimpleNegative", testLetterNameSimpleNegative),
        ("testLetterNameSimplePositive", testLetterNameSimplePositive),
        ("testLetterNameWrapping", testLetterNameWrapping),
    ]
}

extension PitchSpellingCategoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchSpellingCategoryTests = [
        ("testLetterNamePredecessor", testLetterNamePredecessor),
        ("testLetterNameSuccessor", testLetterNameSuccessor),
        ("testNeutralLetterName", testNeutralLetterName),
        ("testPCEight_AFlat", testPCEight_AFlat),
        ("testPCEightNeutral_Nil", testPCEightNeutral_Nil),
        ("testPCEightUp_GSharp", testPCEightUp_GSharp),
        ("testPCFourDown_FFlat", testPCFourDown_FFlat),
        ("testPCFourNeutral_ENatural", testPCFourNeutral_ENatural),
        ("testPCFourUp_DDoubleSharp", testPCFourUp_DDoubleSharp),
        ("testPCOneDown_DFlat", testPCOneDown_DFlat),
        ("testPCOneNeutral_CSharp", testPCOneNeutral_CSharp),
        ("testPCOneUp_BDoubleSharp", testPCOneUp_BDoubleSharp),
        ("testPCThreeDown_FDoubleFlat", testPCThreeDown_FDoubleFlat),
        ("testPCThreeNeutral_EFlat", testPCThreeNeutral_EFlat),
        ("testPCThreeUp_DSharp", testPCThreeUp_DSharp),
        ("testPCTwoDown_EDoubleFlat", testPCTwoDown_EDoubleFlat),
        ("testPCTwoNeutral_DNatural", testPCTwoNeutral_DNatural),
        ("testPCTwoUp_CDoubleSharp", testPCTwoUp_CDoubleSharp),
        ("testPCZeroDown_DDoubleFlat", testPCZeroDown_DDoubleFlat),
        ("testPCZeroNeutral_CNatural", testPCZeroNeutral_CNatural),
        ("testPCZeroUp_BSharp", testPCZeroUp_BSharp),
    ]
}

extension PitchSpellingTendencyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchSpellingTendencyTests = [
        ("testPCEightUpDown_GSharp", testPCEightUpDown_GSharp),
        ("testPCElevenUpDown_BNatural", testPCElevenUpDown_BNatural),
        ("testPCNineDownDown_BDoubleFlat", testPCNineDownDown_BDoubleFlat),
        ("testPCSixUpUp_EDoubleSharp", testPCSixUpUp_EDoubleSharp),
        ("testPCThreeUpDown_EFlat", testPCThreeUpDown_EFlat),
        ("testPCZeroUpDown_CNatural", testPCZeroUpDown_CNatural),
        ("testTendencyComparable", testTendencyComparable),
    ]
}

extension PitchSpellingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchSpellingTests = [
        ("testCDoubleFlatDescription", testCDoubleFlatDescription),
        ("testCDoubleSharpDescription", testCDoubleSharpDescription),
        ("testCFlatDescription", testCFlatDescription),
        ("testCNaturalDescription", testCNaturalDescription),
        ("testCSharpDescription", testCSharpDescription),
        ("testENonTupleFlatDescription", testENonTupleFlatDescription),
        ("testFQuintupleSharpDescription", testFQuintupleSharpDescription),
        ("testGQuadrupleSharpDescription", testGQuadrupleSharpDescription),
        ("testInitJustLetterName", testInitJustLetterName),
        ("testPitchClassCQuarterSharpZeroPointFive", testPitchClassCQuarterSharpZeroPointFive),
        ("testPitchClassCSharpOne", testPitchClassCSharpOne),
        ("testPitchClassCZero", testPitchClassCZero),
        ("testPitchClassDDoubleFlatZero", testPitchClassDDoubleFlatZero),
    ]
}

extension SpelledPitchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpelledPitchTests = [
        ("testANaturalPlusPerfectFourthOctave", testANaturalPlusPerfectFourthOctave),
        ("testBNaturalPlusMajorThird", testBNaturalPlusMajorThird),
        ("testBQuarterSharp", testBQuarterSharp),
        ("testBSharpPtolemaicDown", testBSharpPtolemaicDown),
        ("testCDoubleSharpPlusAugmentedFourth", testCDoubleSharpPlusAugmentedFourth),
        ("testCNaturalDisplacedByMajorSecondDNatural", testCNaturalDisplacedByMajorSecondDNatural),
        ("testCNaturalDisplacedByMinorThirdEFlat", testCNaturalDisplacedByMinorThirdEFlat),
        ("testCNaturalPlusDescendingMajorSecond", testCNaturalPlusDescendingMajorSecond),
        ("testCNaturalPlusMinorSeventh", testCNaturalPlusMinorSeventh),
        ("testComparableDifferentOctave", testComparableDifferentOctave),
        ("testComparableMinorSixth", testComparableMinorSixth),
        ("testComparableSameLetter", testComparableSameLetter),
        ("testComparableSameOctave", testComparableSameOctave),
        ("testCSharpMajorThirdESharp", testCSharpMajorThirdESharp),
        ("testCSharpPlusMajorSecondDSharp", testCSharpPlusMajorSecondDSharp),
        ("testCSharpPlusMinorSecondDNatural", testCSharpPlusMinorSecondDNatural),
        ("testDisplacedByUnisonIsSelf", testDisplacedByUnisonIsSelf),
        ("testENaturalPlusMajorSecond", testENaturalPlusMajorSecond),
        ("testExtrema", testExtrema),
        ("testFNaturalPlusDescendingMajorSecondNoOctaveChange", testFNaturalPlusDescendingMajorSecondNoOctaveChange),
        ("testFNaturalPlusMinorSeventh", testFNaturalPlusMinorSeventh),
        ("testFSharpPlusMajorThirdASharp", testFSharpPlusMajorThirdASharp),
        ("testGSharpPlusDescendingMajorSeventh", testGSharpPlusDescendingMajorSeventh),
        ("testOctaveBBelowMiddleC", testOctaveBBelowMiddleC),
        ("testOctaveBSharp", testOctaveBSharp),
        ("testOctaveCFlat", testOctaveCFlat),
        ("testOctaveCNaturalDown", testOctaveCNaturalDown),
        ("testOctaveCQuarterFlat", testOctaveCQuarterFlat),
        ("testOctaveDAboveMiddleC", testOctaveDAboveMiddleC),
        ("testOctaveMiddleC", testOctaveMiddleC),
    ]
}

extension SpellingInverterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpellingInverterTests = [
        ("testConsistentBasicExample", testConsistentBasicExample),
        ("testCycleCheckFSharpASharpGFlatBFlat", testCycleCheckFSharpASharpGFlatBFlat),
        ("testCycleCheckFSharpASharpGFlatBFlatSubGraphs", testCycleCheckFSharpASharpGFlatBFlatSubGraphs),
        ("testCycleCheckFSharpASharpGFlatBFlatSubGraphsAfterStronglyConnectedComponentsClumped", testCycleCheckFSharpASharpGFlatBFlatSubGraphsAfterStronglyConnectedComponentsClumped),
        ("testDependenciesFSharpASharp", testDependenciesFSharpASharp),
        ("testGroupBuilderSimple", testGroupBuilderSimple),
        ("testGroupBuilderSimple2", testGroupBuilderSimple2),
        ("testGroupBuilderThreeGroupsMoreComplicated", testGroupBuilderThreeGroupsMoreComplicated),
        ("testGroupBuilderThreeGroupsMoreComplicatedPartitionSyntax", testGroupBuilderThreeGroupsMoreComplicatedPartitionSyntax),
        ("testGroupBuilderTwoGroups", testGroupBuilderTwoGroups),
        ("testGroupBuilderTwoGroupsMoreComplicated", testGroupBuilderTwoGroupsMoreComplicated),
        ("testLargeSetOfDyadsWithoutCycles", testLargeSetOfDyadsWithoutCycles),
        ("testMajorThirds", testMajorThirds),
        ("testMinorThirds", testMinorThirds),
        ("testPerfectFourths", testPerfectFourths),
        ("testSemitones", testSemitones),
        ("testSpellingInverterAdjacenciesFSharpASharp", testSpellingInverterAdjacenciesFSharpASharp),
        ("testSpellingInverterEdgesPitchClass11", testSpellingInverterEdgesPitchClass11),
        ("testSpellingInverterPitchClass0", testSpellingInverterPitchClass0),
        ("testSpellingInverterPitchClass1", testSpellingInverterPitchClass1),
        ("testSpellingInverterPitchClass10", testSpellingInverterPitchClass10),
        ("testSpellingInverterPitchClass11", testSpellingInverterPitchClass11),
        ("testSpellingInverterPitchClass2", testSpellingInverterPitchClass2),
        ("testSpellingInverterPitchClass3", testSpellingInverterPitchClass3),
        ("testSpellingInverterPitchClass4", testSpellingInverterPitchClass4),
        ("testSpellingInverterPitchClass5", testSpellingInverterPitchClass5),
        ("testSpellingInverterPitchClass6", testSpellingInverterPitchClass6),
        ("testSpellingInverterPitchClass7", testSpellingInverterPitchClass7),
        ("testSpellingInverterPitchClass8", testSpellingInverterPitchClass8),
        ("testSpellingInverterPitchClass9", testSpellingInverterPitchClass9),
        ("testTones", testTones),
        ("testWeightsDerivationWithSimpleCycle", testWeightsDerivationWithSimpleCycle),
        ("testWeightsFSharpASharp", testWeightsFSharpASharp),
    ]
}

extension UnorderedIntervalDescriptorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnorderedIntervalDescriptorTests = [
        ("testBFlatDSharpAugmentedThird", testBFlatDSharpAugmentedThird),
        ("testCASharpAugmentedSixthDiminishedThird", testCASharpAugmentedSixthDiminishedThird),
        ("testDFSharpMajorThird", testDFSharpMajorThird),
        ("testInitAugmentedUnison", testInitAugmentedUnison),
        ("testInitDoubleAugmentedUnison", testInitDoubleAugmentedUnison),
        ("testInitMinorSecond", testInitMinorSecond),
        ("testInitTripleAugmentedUnison", testInitTripleAugmentedUnison),
        ("testInitUnisonSamePitchClass", testInitUnisonSamePitchClass),
    ]
}

extension WetherfieldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WetherfieldTests = [
        ("testInitDyadNodeCount", testInitDyadNodeCount),
        ("testInitMonadNodeCount", testInitMonadNodeCount),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CompoundIntervalDescriptorTests.__allTests__CompoundIntervalDescriptorTests),
        testCase(FlowNetworkTests.__allTests__FlowNetworkTests),
        testCase(FlowNodeTests.__allTests__FlowNodeTests),
        testCase(LetterNameTests.__allTests__LetterNameTests),
        testCase(PitchSpellingCategoryTests.__allTests__PitchSpellingCategoryTests),
        testCase(PitchSpellingTendencyTests.__allTests__PitchSpellingTendencyTests),
        testCase(PitchSpellingTests.__allTests__PitchSpellingTests),
        testCase(SpelledPitchTests.__allTests__SpelledPitchTests),
        testCase(SpellingInverterTests.__allTests__SpellingInverterTests),
        testCase(UnorderedIntervalDescriptorTests.__allTests__UnorderedIntervalDescriptorTests),
        testCase(WetherfieldTests.__allTests__WetherfieldTests),
    ]
}
#endif
